name: bovine_embryo_survival_prediction
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - opencv
  - pyyaml
  - torchvision
  - pytorch
  - pytorch-cuda=11.6
  - libcufile=1.4.0.31
  - tensorflow
  - cloudpickle
  - xgboost
  - einops

  # dev
  - flake8
  - black


  - pip
  - pip:
    - osfclient
    - ramp-workflow
